AppThreat/vulnerability-db

vdb/lib/config.py, vdb/lib/gha.py
This adds support for GitHub Enterprise instances. The extra check is just to avoid database hickups as GitHub returns sometimes non-existent nodes.
This is required by: https://github.com/ShiftLeftSecurity/sast-scan/pull/344
=> Support GHE

README.md, setup.py, test/data/protobuf-c.json, test/data/redis.json, test/test_source.py, test/test_utils.py, vdb/lib/aqua.py, vdb/lib/utils.py
- Wolfi OS
- Chainguard
- Move namespace to name field for go (Since golang doesn't have a concept of namespace so AppThreat was deviating from other tools such as dependency-track)
=> Wolfi OS + Go namespace to name move

requirements.txt, vdb/lib/utils.py
[`semver-3.0.0`](https://python-semver.readthedocs.io/en/latest/changelog.html#version-3-0-0) has breaking changes.. Especially `isvalid` was renamed to `is_valid`.
=> Allow later semver

.github/workflows/pythonapp.yml, .github/workflows/pythonpublish.yml, pyproject.toml, requirements-dev.txt, requirements.txt, test/test_db.py, vdb/cli.py, vdb/lib/__init__.py, vdb/lib/aqua.py, vdb/lib/config.py, vdb/lib/db.py, vdb/lib/gha.py, vdb/lib/npm.py, vdb/lib/nvd.py, vdb/lib/osv.py, vdb/lib/storage.py, vdb/lib/utils.py
I noticed that msgpack doesn't compress or rewrite the object's keys; so if a packed object had long keys, it was stored as-is. A simple tweak to simplify long repeated keys offered some size reduction.
Old variable names
```
min_affected_version_including=None,
max_affected_version_including=None,
min_affected_version_excluding=None,
max_affected_version_excluding=None,
```
New variable names
```
mii=None,
mai=None,
mie=None,
mae=None,
```
The second bigger compression was achieved with a simple string replacement while storing the description. I experimented with lzma and zlib to store descriptions. While it further reduced the DB size, it increased the db creation time and offered no significant improvements for dep-scan.
For a future iteration, we can experiment with separate vdb …
=> Reduce db size. Lint fixes

pyproject.toml, test/test_source.py, vdb/lib/config.py, vdb/lib/db.py, vdb/lib/osv.py, vdb/lib/storage.py, vdb/lib/utils.py
At some point, cdxgen has stopped generating precise sbom for container images with distro and distro_name qualifiers. This had broken the functionality for container image search for many distros including ubuntu. This PR relaxes by supporting vendor less searches. At the same time, cdxgen is getting fixed to add distro and distro_name qualifiers by parsing os-release info.
=> Support for searching os packages without vendor

pyproject.toml, test/data/SUSE-SU-2015-0439-1.json, test/test_source.py, vdb/lib/aqua.py, vdb/lib/config.py, vdb/lib/osv.py
Fixes #63
We live in a world where distros (even with the word enterprise in the name) do not provide vulnerability information using purl. This makes identifying the package name and version difficult since even versions could have hyphens, alphabets, and colons.
=> Improved version parsing for suse. 

pyproject.toml, test/test_source.py, vdb/lib/osv.py, vdb/lib/utils.py
The best way to understand this PR is to try this search on the master and with this branch.
```
vdb --search "pkg:maven/org.springframework/spring-core@5.2.5?type=jar"
```
The fix version would be missing in the master since we do know or store the fix version correctly while dealing with the versions array.
=> Better logic to handle osv versions list

.github/workflows/pythonapp.yml, pyproject.toml, vdb/lib/__init__.py, vdb/lib/nvd.py, vdb/lib/utils.py
Added backwards-compatible functionality needed for CSAF generation.
=> Include additional metadata in vulnerability occurrences for CSAF.

pyproject.toml, test/test_utils.py, vdb/lib/utils.py
Closes #75 
Changes logic for version_compare in utils to use the mie and mae when they are provided, even if min or max versions are also included. Adds additional tests to demonstrate why this is necessary.
=> Fix/issue 75 version_compare

pyproject.toml, vdb/lib/osv.py
Where there are multiple aliases, we now prefer the CVE alias over others.
```
"aliases": [
"BIT-dotnet-2024-0056",
"BIT-dotnet-sdk-2024-0056",
"CVE-2024-0056"
],
```
=> Prefer CVE alias over others

pyproject.toml, vdb/lib/npm.py
With this fix, we get the correct cvss score returned for certain packages instead of the default 5.0.
```
python depscan/cli.py --purl "pkg:npm/axios@1.5.1" --reports-dir /tmp/reports
```
```
Dependency Scan Results (NPM)
╔══════════════════════════════════════════════════════════════╤═════════════════════╤═══════════════════════════╤════════════════════╤══════════════╗
║ CVE                                                          │ Insights            │ Fix Version               │ Severity           │        Score ║
╟──────────────────────────────────────────────────────────────┼─────────────────────┼───────────────────────────┼────────────────────┼──────────────╢
║ axios@1.5.1 ⬅ CVE-2023-45857                                 │                     │ 1.6.0                     │ MEDIUM …
```
=> npm use cvss attribute if present to extract the score

pyproject.toml, test/test_source.py, vdb/cli.py, vdb/lib/osv.py
=> Handle pysec data with ghsa

test/data/CVE-2015-3192.json, test/data/osv_multi_events.json, test/test_source.py, test/test_utils.py, vdb/lib/__init__.py, vdb/lib/db.py, vdb/lib/nvd.py
Handle legacy CVEs such as `CVE-2015-3192` where only the CPE uri is present in the API json.
=> nvd api fixed version

README.md, contrib/cpe_research.py, vdb/cli.py, vdb/lib/aqua.py, vdb/lib/config.py, vdb/lib/cve.py, vdb/lib/nvd.py, vdb/lib/search.py
With this PR, we can detect git URLs and create pseudo git-based generic purls to help with searches based on vcs and distribution urls.
=> Improve git url detection for generic purls

.github/workflows/pythonapp.yml, pyproject.toml, test/data/osv-npm-star-bug.json, test/test_source.py, test/test_utils.py, vdb/lib/db6.py, vdb/lib/utils.py
An unwanted else block in utils.vers_compare was resulting in false positives while dealing with single version specifiers. This negatively affected ecosystems such as npm.
=> Simplified vers compare to reduce false positives with single vers range

.gitignore, pyproject.toml, test/data/osv-pypi-ujson-bug.json, test/test_source.py, vdb/lib/osv.py
With this PR, the fix version shows up for certain python packages that have a start version of 0.
```
python vdb/cli.py --search "pkg:pypi/ujson@5.2.0"
+----------------+-----------------+--------------------+---------------+---------+------------+---------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Id             | Package         | Affected Version   | Fix Version   | CWE     | Severity   |   Score | Description …
```
=> Fix version was missing for certain packages for osv

test/test_source.py, vdb/cli.py, vdb/lib/aqua.py, vdb/lib/db6.py
=> Ignore suse/suse cvrf. Other performance improvements.

.gitignore, README.md, pyproject.toml, vdb/lib/aqua.py, vdb/lib/config.py, vdb/lib/db6.py
Fixes #174. Users wishing to include suse can set the below environment variable
```
export VDB_INCLUDE_SUSE=true
```
The PR also adds support to ignore individual distros.
=> Support for ignoring specific distro feeds

vdb/cli.py
=> Rich vdb file metadata

README.md, vdb/cli.py
```
python vdb/cli.py --print-vdb-metadata
___
/\  ._  ._  | |_  ._ _   _. _|_
/--\ |_) |_) | | | | (/_ (_|  |_
|   |
VDB Summary
┏━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Property          ┃ Value                                       ┃
┡━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ created_utc       │ 2024-07-16T18:08:18+00:00                   │
├───────────────────┼─────────────────────────────────────────────┤
│ cve_data_count    │ 383611                                      │
├───────────────────┼─────────────────────────────────────────────┤
│ cve_index_count   │ 474004                                      │
├───────────────────┼─────────────────────────────────────────────┤
│ sources           │ ['AquaSource', 'OSVSource', …
```
=> Adds argument to print vdb metadata
