setup.py
test/data/npm_adv_data.json
test/test_db.py
test/test_npm.py
test/test_source.py
test/test_storage.py
test/test_utils.py
vdb/cli.py
vdb/lib/__init__.py
vdb/lib/config.py
vdb/lib/db.py
vdb/lib/gha.py
vdb/lib/npm.py
vdb/lib/nvd.py
vdb/lib/storage.py
vdb/lib/utils.py

Support for fix version

---

requirements.txt
setup.py
test/test_db.py
test/test_utils.py
vdb/lib/__init__.py
vdb/lib/db.py
vdb/lib/nvd.py
vdb/lib/storage.py
vdb/lib/utils.py

Semver with version include/exclude improvements

---

.github/workflows/pythonapp.yml
.github/workflows/pythonpublish.yml
requirements.txt
setup.py
test/test_db.py
vdb/cli.py
vdb/lib/__init__.py
vdb/lib/db.py
vdb/lib/gha.py
vdb/lib/npm.py
vdb/lib/nvd.py
vdb/lib/storage.py
vdb/lib/utils.py

json fallback

---

.github/workflows/pythonapp.yml
setup.py
test/test_db.py
vdb/cli.py
vdb/lib/config.py
vdb/lib/db.py
vdb/lib/storage.py
vdb/lib/utils.py

Track storage position to speed up searches
Optimized chunk size in storage

Performance improvements

---

pyproject.toml
vdb/lib/__init__.py

Fix issue #71 caused by empty dates
Closes #71

Fix handle empty dates.

---

pyproject.toml
test/test_utils.py
vdb/lib/db.py
vdb/lib/osv.py

This is required to make depscan report certain CVEs.
```
python depscan/cli.py --purl "pkg:nuget/System.Net.Http@4.3.0" --reports-dir /mnt/work/sandbox/dotnet-ds/reports                                                 ok  depscan py 
██████╗ ███████╗██████╗ ███████╗ ██████╗ █████╗ ███╗   ██╗
██╔══██╗██╔════╝██╔══██╗██╔════╝██╔════╝██╔══██╗████╗  ██║
██║  ██║█████╗  ██████╔╝███████╗██║     ███████║██╔██╗ ██║
██║  ██║██╔══╝  ██╔═══╝ ╚════██║██║     ██╔══██║██║╚██╗██║
██████╔╝███████╗██║     ███████║╚██████╗██║  ██║██║ ╚████║
╚═════╝ ╚══════╝╚═╝     ╚══════╝ ╚═════╝╚═╝  ╚═╝╚═╝  ╚═══╝
INFO [2024-01-24 15:48:39,383] Performing regular scan for /mnt/work/owasp-depscan/dep-scan using plugin nuget
Dependency Scan Results (NUGET) …
```

Handles version 0 with osv. Perform case insensitive search

---

pyproject.toml
vdb/lib/nvd.py

Regression created with this commit.
https://github.com/AppThreat/vulnerability-db/commit/c43479c082e23dbe54a4b79f62e1d6d5970d765f

Load the db at least once before store

---

.github/workflows/pythonapp.yml
README.md
pyproject.toml
test/data/osv_swift_data.json
test/data/osv_swift_data2.json
test/test_source.py
test/test_utils.py
vdb/cli.py
vdb/lib/aqua.py
vdb/lib/config.py
vdb/lib/db.py
vdb/lib/gha.py
vdb/lib/npm.py
vdb/lib/nvd.py
vdb/lib/osv.py
vdb/lib/storage.py
vdb/lib/utils.py

Adds support for swift from osv
Linting fixes: #74
To test find a cve from osv - https://osv.dev/list?ecosystem=SwiftURL&q=
Use package URL syntax
```
vdb --search "pkg:swift/github.com/vapor/vapor@4.39.0"
vdb --search "pkg:swift/vapor/vapor@4.89.0"
```

Support for swift. Lint fixes

---

vdb/lib/npm.py

Same as https://github.com/AppThreat/vulnerability-db/pull/93 for 6.x

npm use cvss attribute if present to extract the score

---

vdb/lib/npm.py

Same as https://github.com/AppThreat/vulnerability-db/pull/97 for v6

Handle zero scores from npm

---

pyproject.toml
test/test_utils.py
vdb/lib/utils.py

Fix for https://github.com/owasp-dep-scan/dep-scan/issues/281

Replicate false positive

---

test/test_source.py

Additional tests

---

test/data/CVE-2024-25450.json
test/test_source.py
vdb/lib/aqua.py
vdb/lib/cve.py
vdb/lib/osv.py

Both alpine unfixed and Ubuntu with `needs-triage` status are now stored in the DB.

Track alpine unfixed

---

pyproject.toml
test/test_utils.py
vdb/lib/utils.py

Fixes #142, #143

---

pyproject.toml
test/data/MAL-2024-1333.json
test/data/MAL-2024-1396.json
test/test_source.py
vdb/lib/osv.py
vdb/lib/utils.py

Brings OSV fixes to 5.x
#140 
#141

Backported #140, #141

---

pyproject.toml
test/data/GHSA-vc2p-r46x-m3vx.json
test/data/GHSA-xrjj-mj9h-534m.json
test/data/GO-2022-0251.json
test/data/RUSTSEC-2024-0343.json
test/test_source.py
vdb/cli.py
vdb/lib/__init__.py
vdb/lib/aqua.py
vdb/lib/cve.py
vdb/lib/gha.py
vdb/lib/npm.py
vdb/lib/nvd.py
vdb/lib/osv.py
vdb/lib/utils.py

Capture affected modules and functions

---

pyproject.toml
test/data/CVE-2018-9840.json
test/data/CVE-2021-27434.json
test/test_source.py
test/test_utils.py
vdb/lib/__init__.py
vdb/lib/config.py
vdb/lib/cve.py
vdb/lib/db6.py
vdb/lib/nvd.py
vdb/lib/utils.py

Improve quality of cpe, purl_prefix and vers

---

.github/workflows/pythonapp.yml
.github/workflows/pythonpublish.yml

Generate sbom

---

.github/workflows/pythonapp.yml
README.md
pyproject.toml
vdb/cli.py
vdb/lib/config.py
vdb/lib/db6.py

Added api methods to determine db creation time and update needs

---

.github/workflows/pythonapp.yml
test/data/osv-maven-single.json
test/test_source.py
test/test_utils.py
vdb/cli.py
vdb/lib/gha.py
vdb/lib/utils.py

Reproducible with:
```
python vdb/cli.py --search "pkg:maven/org.springframework/spring-core@6.0.13"
```

Single version in ghsa was creating false positives

---

vdb/lib/nvd.py

Example CVE - https://github.com/AppThreat/vuln-list/blob/main/nvd/2023/CVE-2023-35116.json

Ignore withdrawn cve

---

.github/workflows/pythonapp.yml
pyproject.toml
test/data/CVE-2020-25638.json
test/data/CVE-2024-3801.json
test/test_source.py
vdb/lib/aqua.py
vdb/lib/utils.py

Ignores non-fixed and versionless redhat packages to reduce false positives.
Fixes #164 
Fixes #166

Support redhat package fix state and versionless packages

---

test/test_utils.py
vdb/lib/cve.py
vdb/lib/nvd.py
vdb/lib/osv.py
vdb/lib/utils.py

Method to extract affected symbols from nvd description text.

Extract affected symbols for nvd
